config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'teachers#index'
  resources :teachers do
    resources :appointments, only: [:new, :create]
  end

  resources :appointments, only: [:index, :show, :update]

  resources :subjects, only: [:index]

  get 'teach', to: "appointments#teach"
  patch 'accept/:id', to: "appointments#accept", as: :accept
  patch 'decline/:id', to: "appointments#decline", as: :decline
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :teacher
  belongs_to :user
  after_create :default_values
  validates :rating, :inclusion => 1..5, :allow_nil => true

  def default_values
    self.status = "pending" if self.status.nil?
    self.save
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :teachers
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  mount_uploader :picture, PhotoUploader
  belongs_to :subject
  belongs_to :user
  has_many :appointments
  validates :name, presence: true
  validates :description, presence: true
  validates :subject, presence: true
  validates :rate, presence: true
  # has_many :users through: :appointments

  def average_rating
    rating = 0
    number = 0
    appointments.each do |appointment|
      unless appointment.rating.nil?
        rating += appointment.rating
        number += 1
      end
    end
    rating = (rating / number).round unless rating.zero?
    return rating
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :appointments
  has_many :teachers
  # until we need the below line:
  # has_many :teachers, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.where(user_id: current_user.id)
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def edit
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params)
    redirect_to appointment_path(@appointment)
  end

  def new
    @teacher = Teacher.find(params[:teacher_id])
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.teacher = Teacher.find(params[:teacher_id])
    @appointment.user = current_user
    @appointment.save
    redirect_to appointments_path
  end

  def teach
    @appointments = Appointment.where(teacher_id: current_user.teachers)
  end

  def accept
    @appointment = Appointment.find(params[:id])
    @appointment.status = "accepted"
    @appointment.save
    redirect_to teach_path
  end

  def decline
    @appointment = Appointment.find(params[:id])
    @appointment.status = "declined"
    @appointment.save
    redirect_to teach_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :rating)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    if params[:query].present?
      subjects = Subject.where("name ILIKE ?", "%#{params[:query]}%")
      @teachers = []
      subjects.each do |subject|
        @subject = subject
        @teachers << subject.teachers
      end
      @teachers = @teachers.flatten
    end
  end
end

app/controllers/teachers_controller.rb
require "selenium-webdriver"

class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
    @appointment = Appointment.new
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.user = current_user
     driver = Selenium::WebDriver.for :chrome

    driver.navigate.to "https://www.inaturalist.org/computer_vision_demo"
    file =  @teacher.picture.file.file

    button = driver.find_element(:xpath => "//*[@id='app']/div/div/input")
    button.send_key file
    classify = driver.find_element(:class => "classify")
    sleep(2)
    classify.click
    driver.quit
    if @teacher.save
      redirect_to teacher_path(@teacher)
    else
      render :new
    end
  end

  def edit
    @teacher = Teacher.find(params)
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to teacher_path(@teacher)
    else
      render :edit
    end
  end

  def delete
  end

  private

  def teacher_params
    params.require(:teacher).permit(:name, :description, :subject_id, :picture, :rate, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
_form.html.erb

app/views/appointments/index.html.erb
<div class="appointments-wrapper">
  <div class="appointments-container">
    <h2>Your appointments</h2>
    <div class="tabs">
      <a href="<%= appointments_path %>" class="tab active" id="learn">Learning</a>
      <a href="<%= teach_path %>" class="tab" id="teach">Teaching</a>
    </div>
    <ul class="inbox">
      <% @appointments.each do  |appointment| %>
      <li class="message">
        <%= link_to appointment_path(appointment)  do %>
        <%=cl_image_tag appointment.teacher.picture, class: "avatar-large" %>
        <% end %>
        <div class="message-name">
          <h3><%=  appointment.teacher.name %></h3>
        </div>
        <div class="message-body">
          <p><strong><%= "Subject: #{appointment.teacher.subject.name}  "  %></strong></p>
          <p>
            <%= "Date: #{appointment.date} "%>
          </p>
        </div>
        <div class="message-status">
          <% case appointment.status %>
          <% when "pending" %>
          <p class="status pending">Pending</p>
          <%when "accepted" %>
          <p class="status accepted">Accepted</p>
          <% when "declined" %>
          <p class="status declined">Declined</p>
          <%end %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/appointments/new.html.erb
  <%= simple_form_for [@teacher, @appointment] do |f| %>
  <%= f.input :date %>
  <%= f.submit "submit", class: "btn btn-primary" %>
<% end %>

app/views/appointments/show.html.erb
<div class="flex-container">
  <div class="flex-subject-description">
    <div class="left-column">
      <h3><%= name = @appointment.teacher.name.split(" ").map { |name| name.capitalize }.join(" ") %></h3>
      <%=  cl_image_tag @appointment.teacher.picture, height: 300, width: 300, crop: :fill, class: "teacher-photo" %>
    </div>
    <div class="left-column">
      <h3>Subject taught</h3>
      <p>
        <%= @appointment.teacher.subject.name.capitalize %>
      </p>
    </div>
    <div class="left-column">
      <h3>Lesson Description</h3>
      <p>
        <%= @appointment.teacher.description %>
      </p>
    </div>
    <div class="left-column">
      <h3>Rate the teacher!</h3>
      <% if @appointment.status == "pending" || @appointment.status == "declined" %>
      <p>You can't rate the teacher now.</p>
      <%elsif @appointment.rating.nil? %>
      <%= simple_form_for [@appointment] do |f| %>
      <%= f.input :rating, as: :select, :collection => (1..5).to_a %>
      <%= f.button :submit, "Rate!", class: "book btn-main-base btn-main-styled" %>
      <% end %>
      <% else %>
      <p>You have assigned this teacher a rating of
        <%=  @appointment.rating%>
      </p>
      <% end %>
    </div>
  </div>
  <div class="flex-info">
    <div class="right-column">
      <h3>Rate</h3>
      <p>My hourly rate is EUR
        <%= @appointment.teacher.rate %>.
      </p>
    </div>
  </div>
</div>

app/views/appointments/teach.html.erb
<div class="appointments-wrapper">
  <div class="appointments-container">
    <h2>Your appointments</h2>
    <div class="tabs">
      <a href="<%= appointments_path %>" class="tab" id="learn">Learning</a>
      <a href="<%= teach_path %>" class="tab active" id="teach">Teaching</a>
    </div>
    <ul class="inbox" id="inbox-teaching">
      <% @appointments.each do  |appointment| %>
      <li class="message">
        <%=  image_tag "morty.png", class: "avatar-large" %>
        <div class="message-name">
          <h3><%=  appointment.user.email %></h3>
        </div>
        <div class="message-body">
          <p><strong><%= "Subject: #{appointment.teacher.subject.name}  "  %></strong></p>
          <p>
            <%= "Date: #{appointment.date} "%>
          </p>
        </div>
        <div class="message-status">
          <% case appointment.status %>
          <% when "pending" %>
          <%= link_to "Accept",accept_path(:id => appointment),:method => :patch, class: "btn btn-success btn-sm",id: "accept"  %>
          <%= link_to "Decline", decline_path(:id => appointment),:method => :patch, class: "btn btn-danger btn-sm", id: "decline" %>
          <%when "accepted" %>
          <p class="status accepted">You have accepted</p>
          <% when "declined" %>
          <p class="status declined">You have declined</p>
          <%end %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Find Your Teacher</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application' %>
  <!-- NEW! -->
  <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>

<body>
  <%= render 'shared/flashes' %>
  <%= render 'shared/navbar' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>


</html>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="left">
    <%= form_tag subjects_path, method: :get do %>
    <div class="text_with_button">
      <%= text_field_tag :query,params[:query],class: "form-control",placeholder: "What do you want to learn?" %>
      <button>
        <%= image_tag "teacher.png", height: 50 %>
      </button>
      <% end %>
    </div>
  </div>
  <!-- Righ t Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <!-- Links when logged in -->
    <%= link_to "Become a teacher", new_teacher_path, class: "navbar-wagon-item navbar-teacher-link" %>
    <%= link_to "Home", teachers_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Appointments", appointments_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "morty.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>
            <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to "Become a teacher", new_teacher_path, class: "navbar-wagon-item navbar-teacher-link" %>
        </li>
        <li>
          <%= link_to "Home", teachers_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to "Appointments", appointments_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/subjects/index.html.erb
<div class="container">
  <% if @subject.present? %>
  <h2><%= "Result - #{ pluralize @teachers.size, "Teacher" }" %></h2>
  <div class="row">
    <% @teachers.each do |teacher| %>
    <div class="col-xs-12 col-sm-3">
      <% if teacher.picture.model[:picture].nil? %>
      <% array_image = (1..700).to_a %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://picsum.photos/200/300/?image=<%= array_image.sample %>');">
        <% else %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path teacher.picture%>');">
          <% end %>
          <%= image_tag "#{teacher.subject.name.downcase}.png",height: 50, width: 55, :class => "style_image" %>
          <%= link_to "", teacher_path(teacher), class: 'card-link' %>
        </div>
        <div class="subject-color-cards" style="color: rgb(165, 41, 3);">
          <h3><%= teacher.subject.name.capitalize%></h3>
        </div>
        <div class="subject-description">
          <h2><%= "Learn #{teacher.subject.name.capitalize} From #{teacher.name}" %></h2>
          <%if teacher.average_rating.zero? %>
          <h2>
            <% 5.times do %>
            <i class="fa fa-star" style="color: #cacccd"></i>
            <% end %>
          </h2>
          <% else %>
          <h2>
          <% teacher.average_rating.times do  %>

            <i class="fa fa-star" style="color: #ffb400"></i>
            <% end %>
            <% (5 - teacher.average_rating).times do %>
            <i class="fa fa-star" style="color: #cacccd"></i>
            <%end %>
            </h2>
          <%end %>
        </div>
      </div>
      <% end %>
    </div>
    <% else %>
    <h2>No results found</h2>
    <% end %>
  </div>

app/views/teachers/_form.html.erb
<div class="sign-up-form">
  <%= simple_form_for [@teacher] do |f| %>
    <%= f.input :name , label: 'Full Name:', required: false %>
    <%= f.association :subject, as: :select, label: 'Subject you teach:', required: false %>
    <%= f.input :description, :input_html => { 'rows' => 10}, label: 'Full description of your lesson:', required: false %>
    <%= f.input :rate ,as: :currency, label: 'Your hourly rate:', required: false %>
    <%= f.input :picture, label: 'Your profile picture:', required: false %>
    <%= f.input :picture_cache, as: :hidden %>
    <%= f.submit "Teach now!", class: "button btn-main-base btn-main-styled"%>
  <% end %>
</div>

app/views/teachers/edit.html.erb
<h1>Teacher#edit</h1>
<p>Find me in app/views/teacher/edit.html.erb</p>

app/views/teachers/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url('<%= image_path 'education.jpg' %>');">
  <div class="banner-content">
    <h1>Find Your Teacher</h1>
    <p>You can learn from the local people now!</p>
    <%= form_tag subjects_path, method: :get do %>
    <div class="banner-search-bar">
      <%= text_field_tag :query,params[:query],class: "form-control form-inline",placeholder: "What do you want to learn?" %>
      <button class="btn-main-base btn-main-styled"> Search </button>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <h2>Our teachers</h2>
  <div class="row">
    <% @teachers.each do |teacher| %>
    <div class="col-xs-12 col-sm-3">
      <% if teacher.picture.model[:picture].nil? %>
      <% array_image = (1..700).to_a %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://picsum.photos/200/300/?image=<%= array_image.sample %>');">
        <% else %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path teacher.picture%>');">
          <%end %>
          <%= image_tag "#{teacher.subject.name.downcase}.png",height: 50, width: 55, :class => "style_image" %>
          <%= link_to "", teacher_path(teacher), class: 'card-link' %>
        </div>
        <div class="subject-color-cards" style="color: rgb(165, 41, 3);">
          <h3> <%= teacher.subject.name.capitalize%></h3>
        </div>
        <div class="subject-description">
          <h2><%= "Learn #{teacher.subject.name.capitalize} From #{teacher.name}" %></h2>
          <%if teacher.average_rating.zero? %>
          <h2>
            <% 5.times do %>
            <i class="fa fa-star" style="color: #cacccd"></i>
            <%end %>
          </h2>
          <% else %>
          <h2>
          <% teacher.average_rating.times do  %>
            <i class="fa fa-star" style="color: #ffb400"></i>
            <%end %>
            <% (5 - teacher.average_rating).times do %>
            <i class="fa fa-star" style="color: #cacccd"></i>
            <%end %>
            </h2>
          <%end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 col-sm-6">
      <h2 align="center">Sign up as our teacher!</h2>
      <%= render 'form' %>
      <% @teacher.errors %>
    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="flex-container">
  <div class="flex-subject-description">
    <%=  cl_image_tag @teacher.picture, height: 150, width: 150, crop: :fill, class: "teacher-photo" %>
    <div class="left-column">
      <h3><%= name = @teacher.name.split(" ").map { |name| name.capitalize }.join(" ") %></h3>
    </div>
    <div class="left-column">
      <h3>Lesson Description</h3>
      <p>
        <%= @teacher.description %>
      </p>
    </div>
  </div>
  <div class="flex-info">
    <div class="right-column">
      <h3>Subject taught</h3>
      <p>
        <%= @teacher.subject.name.capitalize %>
      </p>
    </div>
    <div class="right-column">
      <h3>Rate</h3>
      <p>My hourly rate is $
        <%= @teacher.rate %>.
      </p>
    </div>
    <div class="right-column">
      <%if current_user.teachers.include?(@teacher) %>
      <br>
      <p>This is your profile</p>
      <% else %>
      <h3>Calendar</h3>
      <%= simple_form_for [@teacher, @appointment] do |f| %>
      <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.submit "Book now!", class: "button btn-main-base btn-main-styled" %>
      <% end %>
      <% end %>
      <br>
    </div>
  </div>
</div>